name: Brim

on:
  pull_request:
  push:
    branches:
      - master
      - smoketest

defaults:
 run:
   shell: bash

jobs:
  smoketest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    env:
        PACKAGE_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v1
      - run: sudo ./smoketest.sh
